// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "CommonUserWidget.h"
#include "HUDWidget.generated.h"

class UProgressBar;

UCLASS(Abstract)
class NAKEDDESIRE_API UHUDWidget : public UCommonUserWidget
{
	GENERATED_BODY()
	
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UProgressBar> EmbarrassmentBar;
	
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UProgressBar> EnergyBar;
	
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UProgressBar> StaminaBar;
	
protected:
	virtual void NativeConstruct() override;
	
private:
	UFUNCTION()
	void OnEmbarrassmentUpdated(float CurrentValue, float MaxValue);
	
	UFUNCTION()
	void OnEnergyUpdated(float CurrentValue, float MaxValue);
	
	UFUNCTION()
	void OnStaminaUpdated(float CurrentValue, float MaxValue);
};
