#pragma once

#include "CoreMinimal.h"
#include "NakedDesire/Clothing/ClothingSlotType.h"
#include "NakedDesire/Items/ItemDefinition.h"
#include "SexToyItem.generated.h"

UCLASS()
class NAKEDDESIRE_API USexToyItem : public UItemDefinition
{
	GENERATED_BODY()

public:
	virtual TSubclassOf<UItemInstance> GetInstanceClass() const override;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Sex Toy")
	float LustModifier = 0.0f;
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Sex Toy")
	float EmbarrassmentModifier = 0.0f;
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Sex Toy")
	float PulseModifier = 0.0f;
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Sex Toy")
	bool HasVibration = false;
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Sex Toy")
	EClothingSlotType SlotType = EClothingSlotType::Anal;
};
