// © 2025 Naked People Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/GameModeBase.h"
#include "NakedDesireGameMode.generated.h"

class UGlobalSaveGameData;
class AItemPickup;

UCLASS(MinimalAPI)
class ANakedDesireGameMode : public AGameModeBase
{
	GENERATED_BODY()
	
public:
	int NoticeCount = 0;
	
	void RestartGame();

protected:
	virtual void BeginPlay() override;

private:
	UPROPERTY(EditDefaultsOnly, Category = "Items")
	TSubclassOf<AItemPickup> ItemPickupClass;
	
	void SpawnSavedWorldItems(UGlobalSaveGameData* SaveGameData);
};



