// © 2025 Naked People Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "ClothingSlotType.h"
#include "Engine/DataAsset.h"
#include "ClothingSlotWidgetsInfo.generated.h"

USTRUCT(BlueprintType)
struct NAKEDDESIRE_API FClothingSlotWidgetData
{
	GENERATED_BODY()

	UPROPERTY(EditDefaultsOnly)
	UTexture2D* PlaceholderIcon = nullptr;
};

UCLASS()
class NAKEDDESIRE_API UClothingSlotInfo : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	UPROPERTY(EditDefaultsOnly)
	TMap<EClothingSlotType, FClothingSlotWidgetData> ClothingSlotsData;
};
