#pragma once

#include "CoreMinimal.h"
#include "CommonUserWidget.h"
#include "GameLayoutWidget.generated.h"

class UInventoryScreenWidget;
class UHUDWidget;
class UCommonActivatableWidgetStack;

UCLASS()
class NAKEDDESIRE_API UGameLayoutWidget : public UCommonUserWidget
{
	GENERATED_BODY()
	
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UCommonActivatableWidgetStack> WidgetStack;
	
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UHUDWidget> HUD;
	
	UPROPERTY(EditDefaultsOnly, Category = "UI")
	TSubclassOf<UInventoryScreenWidget> InventoryScreenWidgetClass;
	
	UPROPERTY()
	TObjectPtr<UInventoryScreenWidget> InventoryScreenWidget;
	
public:
	void OpenInventory();
};
