// © 2025 Naked People Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "StartingSaveData.generated.h"

class UPhoneItemDefinition;
class UItemDefinition;

UCLASS()
class NAKEDDESIRE_API UStartingSaveData : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	UPROPERTY(EditDefaultsOnly, Category = "Starting State")
	TArray<TObjectPtr<UItemDefinition>> EquippedItems;
	
	UPROPERTY(EditDefaultsOnly, Category = "Starting State")
	TArray<TObjectPtr<UItemDefinition>> WardrobeItems;
	
	UPROPERTY(EditDefaultsOnly, Category = "Starting State")
	TObjectPtr<UPhoneItemDefinition> Phone;
};