// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "MissionsConfig.generated.h"

class UMission;

USTRUCT()
struct NAKEDDESIRE_API FMissionsConfigItem
{
	GENERATED_BODY()
	
	UPROPERTY(EditDefaultsOnly, Instanced)
	TArray<UMission*> Missions;
};

/**
 * 
 */
UCLASS()
class NAKEDDESIRE_API UMissionsConfig : public UPrimaryDataAsset
{
	GENERATED_BODY()
	
public:
	UPROPERTY(EditDefaultsOnly)
	TArray<FMissionsConfigItem> DailyMissions;
	
	UPROPERTY(EditDefaultsOnly)
	TArray<FMissionsConfigItem> WeeklyMissions;
};
