#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"
#include "ItemInstance.generated.h"

UCLASS(Abstract)
class NAKEDDESIRE_API UItemInstance : public UObject
{
	GENERATED_BODY()
	
public:
	virtual void PostInitProperties() override;
	virtual void PostDuplicate(EDuplicateMode::Type DuplicateMode) override;

	UFUNCTION(BlueprintPure, Category = "Item")
	FGuid GetInstanceID() const { return InstanceID; }
	
private:
	UPROPERTY(VisibleAnywhere, SaveGame, BlueprintReadOnly, Category = "Item", meta = (AllowPrivateAccess = "true"))
	FGuid InstanceID;
};
