// © 2025 Naked People Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "CommonButtonBase.h"
#include "TextButton.generated.h"

class UCommonTextBlock;

UCLASS(Abstract)
class NAKEDDESIRE_API UTextButton : public UCommonButtonBase
{
	GENERATED_BODY()
	
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UCommonTextBlock> TextBlock;
	
	UPROPERTY(EditAnywhere, Category = "UI")
	FText Text = FText::FromString(TEXT("Button"));
	
public:
	void SetIsActive(bool Value);
	
protected:
	virtual void NativePreConstruct() override;
	virtual void NativeOnCurrentTextStyleChanged() override;
	virtual void NativeOnHovered() override;
	virtual void NativeOnUnhovered() override;
	
private:
	bool IsActive = false;
};
