#pragma once

#include "CoreMinimal.h"
#include "NakedDesire/Items/ItemInstance.h"
#include "ClothingItemInstance.generated.h"

class UClothingItem;

UCLASS(BlueprintType)
class NAKEDDESIRE_API UClothingItemInstance : public UItemInstance
{
	GENERATED_BODY()
	
public:
	UPROPERTY(BlueprintReadOnly, Category = "Clothing Item")
	float Condition = 1.0f;
	
	UClothingItem* GetClothingItem() const { return ClothingItem; }
	
protected:
	UPROPERTY(BlueprintReadOnly, Category = "Clothing Item")
	TObjectPtr<UClothingItem> ClothingItem;
	
	UPROPERTY(BlueprintReadOnly, Category = "Clothing Item")
	TArray<TObjectPtr<UItemInstance>> StoredItems;
};
