#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "PlayerCinematic.generated.h"

class ANakedDesireCharacter;
class UClothingVisualsComponent;
class UCensorshipComponent;
class UStaticMeshComponent;

UCLASS()
class NAKEDDESIRE_API APlayerCinematic : public ACharacter
{
	GENERATED_BODY()

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, meta = (AllowPrivateAccess = true), Category = "Clothing")
	UClothingVisualsComponent* ClothingVisualsComponent;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, meta = (AllowPrivateAccess = true), Category = "Censorship")
	UStaticMeshComponent* BoobLCensorship;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, meta = (AllowPrivateAccess = true), Category = "Censorship")
	UStaticMeshComponent* BoobRCensorship;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, meta = (AllowPrivateAccess = true), Category = "Censorship")
	UStaticMeshComponent* VaginaCensorship;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, meta = (AllowPrivateAccess = true), Category = "Censorship")
	UStaticMeshComponent* AnalCensorship;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, meta = (AllowPrivateAccess = true), Category = "Censorship")
	UCensorshipComponent* CensorshipComponent;

	UPROPERTY()
	ANakedDesireCharacter* Player;

public:
	APlayerCinematic();

	virtual void BeginPlay() override;
};