// © 2025 Naked People Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Wardrobe.generated.h"

class UClothingItemInstance;

UCLASS(Blueprintable)
class NAKEDDESIRE_API AWardrobe : public AActor
{
	GENERATED_BODY()
	
public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Instanced)
	TArray<TObjectPtr<UClothingItemInstance>> ClothingItems;
	
	void AddItem(UClothingItemInstance* ClothingItemInstance);
	void RemoveItem(UClothingItemInstance* ClothingItemInstance) const;
	
protected:
	virtual void BeginPlay() override;
};
