// © 2025 Naked People Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "CommonUserWidget.h"
#include "NakedDesire/Clothing/ClothingSlotType.h"
#include "EquipmentSlotMenuWidget.generated.h"

class ANakedDesireCharacter;
class UButton;

UCLASS(Abstract)
class NAKEDDESIRE_API UEquipmentSlotMenuWidget : public UCommonUserWidget
{
	GENERATED_BODY()
	
public:
	void Init(EClothingSlotType InSlotType);

	EClothingSlotType GetSlotType() const { return SlotType; }

	DECLARE_MULTICAST_DELEGATE(FOnActionPerformed);
	FOnActionPerformed OnActionPerformed;

protected:
	virtual void NativeConstruct() override;

private:
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UButton> DropClothingBtn;

	UPROPERTY()
	TObjectPtr<ANakedDesireCharacter> Player;

	UPROPERTY()
	EClothingSlotType SlotType;

	UFUNCTION()
	void OnDropClothingClicked();
};
