// © 2025 Naked People Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "CommonActivatableWidget.h"
#include "CreditsWidget.generated.h"

class UButton;

// Credits screen. Pushed onto a stack by the menu; the Back button closes it.
UCLASS(Abstract)
class NAKEDDESIRE_API UCreditsWidget : public UCommonActivatableWidget
{
	GENERATED_BODY()

protected:
	virtual void NativeOnActivated() override;

private:
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UButton> BackButton;

	UFUNCTION()
	void HandleBackClicked();
};