// © 2025 Naked People Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "NakedDesire/UI/Phone/PhoneAppWidget.h"
#include "ForumAppWidget.generated.h"

class UButton;
class UWidgetSwitcher;

// The forum app (GDD §13). Hosts the two bottom tabs the forum surface is scoped to — the commission
// board and the player's own profile (§13.3) — as pages of a switcher. Page content lives in BP:
// the Commissions page is a UForumCommissionsWidget; the Profile page is a placeholder until the
// profile / followers systems land (Phase 8). This shell only drives tab selection.
UCLASS()
class NAKEDDESIRE_API UForumAppWidget : public UPhoneAppWidget
{
	GENERATED_BODY()

protected:
	virtual void NativeOnInitialized() override;

private:
	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UWidgetSwitcher> TabSwitcher;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UButton> CommissionsTabButton;

	UPROPERTY(meta = (BindWidget))
	TObjectPtr<UButton> ProfileTabButton;

	UFUNCTION()
	void ShowCommissions();

	UFUNCTION()
	void ShowProfile();
};