#pragma once

#include "CoreMinimal.h"
#include "GameFramework/HUD.h"
#include "NakedDesireHUD.generated.h"

class UGameLayoutWidget;

UCLASS()
class NAKEDDESIRE_API ANakedDesireHUD : public AHUD
{
	GENERATED_BODY()
	
public:
	UGameLayoutWidget* GetGameLayoutWidget() const { return GameLayoutWidget; }
	
protected:
	UPROPERTY(EditDefaultsOnly, Category = "UI")
	TSubclassOf<UGameLayoutWidget> GameLayoutWidgetClass;
	
	virtual void BeginPlay() override;
	
private:
	UPROPERTY()
	TObjectPtr<UGameLayoutWidget> GameLayoutWidget;
};
