// © 2025 Naked People Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "LocationTrigger.generated.h"

class ULocationData;
class UBoxComponent;

UCLASS()
class NAKEDDESIRE_API ALocationTrigger : public AActor
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly, meta = (AllowPrivateAccess))
	UBoxComponent* BoxTrigger;

	UPROPERTY(EditAnywhere)
	ULocationData* LocationData;

public:
	ALocationTrigger();

	ULocationData* GetLocationData() const;
};
