// © 2025 Naked People Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/HUD.h"
#include "MainMenuHUD.generated.h"

class UMainMenuWidget;

// HUD for the main-menu map. Creates the front-end widget and routes input to it.
// Assign this (or a BP child) as the HUD class on the MainMenu map's GameMode.
UCLASS()
class NAKEDDESIRE_API AMainMenuHUD : public AHUD
{
	GENERATED_BODY()

protected:
	virtual void BeginPlay() override;

	UPROPERTY(EditDefaultsOnly, Category = "UI")
	TSubclassOf<UMainMenuWidget> MainMenuWidgetClass;

private:
	UPROPERTY()
	TObjectPtr<UMainMenuWidget> MainMenuWidget;
};