// © 2025 Naked People Team. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "ClothingSlotType.h"
#include "Engine/DataAsset.h"
#include "ClothingSlotsData.generated.h"

USTRUCT()
struct NAKEDDESIRE_API FClothingSlotData
{
	GENERATED_BODY()
	
	FClothingSlotData()
	{
	}
	
	UPROPERTY(EditDefaultsOnly, Category = "Clothing")
	TObjectPtr<UTexture2D> Icon;
	
	UPROPERTY(EditDefaultsOnly, Category = "Clothing")
	FText Name;
};

UCLASS()
class NAKEDDESIRE_API UClothingSlotsData : public UPrimaryDataAsset
{
	GENERATED_BODY()
	
public:
	UPROPERTY(EditDefaultsOnly, Category = "Clothing")
	TMap<EClothingSlotType, FClothingSlotData> Slots;
};
